export const tasks = [
  {
    projectDelivery: "Project A",
    project: "Project ABC",
    label: "Task",
    status: "Completed",
    year: 2023,
    week: 20,
    worklogs: {
      Monday: 28800,
      Tuesday: 28800,
      Wednesday: 28800,
      Thursday: 28800,
      Friday: 28800,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project B",
    project: "Project XYZ",
    label: "Task",
    status: "In Progress",
    year: 2023,
    week: 21,
    worklogs: {
      Monday: 28800,
      Tuesday: 25200,
      Wednesday: 28800,
      Thursday: 21600,
      Friday: 25200,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project C",
    project: "Project PQR",
    label: "Bug Fix",
    status: "In Progress",
    year: 2023,
    week: 22,
    worklogs: {
      Monday: 21600,
      Tuesday: 28800,
      Wednesday: 28800,
      Thursday: 25200,
      Friday: 21600,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project D",
    project: "Project MNO",
    label: "Enhancement",
    status: "Completed",
    year: 2023,
    week: 23,
    worklogs: {
      Monday: 28800,
      Tuesday: 25200,
      Wednesday: 21600,
      Thursday: 25200,
      Friday: 28800,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project E",
    project: "Project UVW",
    label: "Task",
    status: "In Progress",
    year: 2023,
    week: 24,
    worklogs: {
      Monday: 28800,
      Tuesday: 25200,
      Wednesday: 21600,
      Thursday: 25200,
      Friday: 28800,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project F",
    project: "Project JKL",
    label: "Task",
    status: "In Progress",
    year: 2023,
    week: 25,
    worklogs: {
      Monday: 21600,
      Tuesday: 28800,
      Wednesday: 21600,
      Thursday: 28800,
      Friday: 25200,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project X",
    project: "Project Alpha",
    label: "Task 1",
    status: "Completed",
    year: 2023,
    week: 27,
    worklogs: {
      Monday: 25200,
      Tuesday: 21600,
      Wednesday: 25200,
      Thursday: 28800,
      Friday: 21600,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project Y",
    project: "Project Beta",
    label: "Task 2",
    status: "In Progress",
    year: 2023,
    week: 28,
    worklogs: {
      Monday: 28800,
      Tuesday: 25200,
      Wednesday: 25200,
      Thursday: 21600,
      Friday: 28800,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project Z",
    project: "Project Gamma",
    label: "Task 3",
    status: "In Progress",
    year: 2023,
    week: 29,
    worklogs: {
      Monday: 28800,
      Tuesday: 25200,
      Wednesday: 21600,
      Thursday: 25200,
      Friday: 28800,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project X",
    project: "Project Delta",
    label: "Task 4",
    status: "Completed",
    year: 2023,
    week: 30,
    worklogs: {
      Monday: 21600,
      Tuesday: 28800,
      Wednesday: 25200,
      Thursday: 21600,
      Friday: 25200,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project Y",
    project: "Project Epsilon",
    label: "Task 5",
    status: "In Progress",
    year: 2023,
    week: 31,
    worklogs: {
      Monday: 21600,
      Tuesday: 25200,
      Wednesday: 28800,
      Thursday: 28800,
      Friday: 25200,
      Saturday: 0,
      Sunday: 0,
    },
  },
  {
    projectDelivery: "Project Z",
    project: "Project Zeta",
    label: "Task 6",
    status: "Completed",
    year: 2023,
    week: 32,
    worklogs: {
      Monday: 28800,
      Tuesday: 25200,
      Wednesday: 21600,
      Thursday: 21600,
      Friday: 28800,
      Saturday: 0,
      Sunday: 0,
    },
  },
];

export const tasks2 = [
  {
    projectDelivery: "Project A",
    project: "Project ABC",
    label: "Task 1",
    createdBy: "John",
    assignee: "Alice",
    isPublic: true,
    estimatedDays: 5,
    consumedDays: 4,
    inputedDays: 4,
    firstInputDate: "2023-05-01",
    status: "Completed",
  },
  {
    projectDelivery: "Project B",
    project: "Project XYZ",
    label: "Task 2",
    createdBy: "Jane",
    assignee: "Bob",
    isPublic: false,
    estimatedDays: 7,
    consumedDays: 3,
    inputedDays: 3,
    firstInputDate: "2023-05-02",
    status: "In Progress",
  },
  {
    projectDelivery: "Project C",
    project: "Project PQR",
    label: "Bug Fix",
    createdBy: "Mike",
    assignee: "Sarah",
    isPublic: true,
    estimatedDays: 3,
    consumedDays: 2,
    inputedDays: 2,
    firstInputDate: "2023-05-03",
    status: "In Progress",
  },
  {
    projectDelivery: "Project D",
    project: "Project MNO",
    label: "Enhancement",
    createdBy: "David",
    assignee: "Emily",
    isPublic: true,
    estimatedDays: 6,
    consumedDays: 6,
    inputedDays: 6,
    firstInputDate: "2023-05-04",
    status: "Completed",
  },
  {
    projectDelivery: "Project E",
    project: "Project UVW",
    label: "Task 5",
    createdBy: "Alex",
    assignee: "Olivia",
    isPublic: false,
    estimatedDays: 2,
    consumedDays: 1,
    inputedDays: 1,
    firstInputDate: "2023-05-05",
    status: "In Progress",
  },
  {
    projectDelivery: "Project F",
    project: "Project JKL",
    label: "Task 6",
    createdBy: "Peter",
    assignee: "Sophia",
    isPublic: true,
    estimatedDays: 4,
    consumedDays: 3,
    inputedDays: 3,
    firstInputDate: "2023-05-06",
    status: "Completed",
  },
  {
    projectDelivery: "Project X",
    project: "Project Alpha",
    label: "Task 7",
    createdBy: "John",
    assignee: "Alice",
    isPublic: true,
    estimatedDays: 5,
    consumedDays: 4,
    inputedDays: 4,
    firstInputDate: "2023-05-07",
    status: "Completed",
  },
  {
    projectDelivery: "Project Y",
    project: "Project Beta",
    label: "Task 8",
    createdBy: "Jane",
    assignee: "Bob",
    isPublic: false,
    estimatedDays: 7,
    consumedDays: 3,
    inputedDays: 3,
    firstInputDate: "2023-05-08",
    status: "In Progress",
  },
  {
    projectDelivery: "Project Z",
    project: "Project Gamma",
    label: "Task 9",
    createdBy: "Mike",
    assignee: "Sarah",
    isPublic: true,
    estimatedDays: 3,
    consumedDays: 2,
    inputedDays: 2,
    firstInputDate: "2023-05-09",
    status: "In Progress",
  },
  {
    projectDelivery: "Project X",
    project: "Project Delta",
    label: "Task 10",
    createdBy: "David",
    assignee: "Emily",
    isPublic: true,
    estimatedDays: 6,
    consumedDays: 6,
    inputedDays: 6,
    firstInputDate: "2023-05-10",
    status: "Completed",
  },
  {
    projectDelivery: "Project Y",
    project: "Project Epsilon",
    label: "Task 11",
    createdBy: "Alex",
    assignee: "Olivia",
    isPublic: false,
    estimatedDays: 2,
    consumedDays: 1,
    inputedDays: 1,
    firstInputDate: "2023-05-11",
    status: "In Progress",
  },
  {
    projectDelivery: "Project Z",
    project: "Project Zeta",
    label: "Task 12",
    createdBy: "Peter",
    assignee: "Sophia",
    isPublic: true,
    estimatedDays: 4,
    consumedDays: 3,
    inputedDays: 3,
    firstInputDate: "2023-05-12",
    status: "Completed",
  },
];
